import { Player } from './player/player.js';
import { PlayerStateMachine, PLAYER_STATES } from './player/playerStateMachine.js';
import { PlayerAnimator, PLAYER_ANIMATIONS } from './player/playerAnimator.js';
import { resolveCircleMovement } from './player/collision.js';
import { inventory } from './inventory/inventory.js';
import { Furnace } from './crafting/furnace.js';
import { QuestManager } from './quests/questManager.js';
import { CutsceneManager } from './cinematic/cutsceneManager.js';
import { SaveManager } from './save/saveManager.js';
import { EnemyAI } from './enemies/enemyAI.js';
import { spawnMob } from './enemies/mobSpawner.js';
import { Boss } from './enemies/boss.js';
import { Elite } from './enemies/elite.js';
import { MiniBoss } from './enemies/miniBoss.js';
import { ENEMIES } from './data/enemies.js';
import { Sword } from './combat/sword.js';
import { Pistol } from './combat/pistol.js';
import { calcDamage } from './combat/damage.js';
import { updateHUD } from './ui/hud.js';
import { renderInventory } from './ui/inventoryUI.js';
import { renderRecipes } from './ui/craftingUI.js';
import { showNotif } from './ui/ui.js';
import { rollLoot } from './data/lootTables.js';
import { AudioManager } from './audio/audioManager.js';
import { DayNight } from './world/dayNight.js';
import { Weather } from './world/weather.js';
import { WorldStreaming } from './world/worldStreaming.js';
import { Train } from './train/train.js';
import { TrainDamage } from './train/trainDamage.js';
import { PlayerEquipment } from './player/equipment.js';
import { consumeItem } from './inventory/consumables.js';
import { ResourceNode } from './resources/resourceNode.js';
import { resourceDefinition } from './data/resources.js';
import { ConstructionManager } from './world/construction.js';
import { FogOfWar } from './world/fogOfWar.js';
import { TravelEventManager } from './world/travelEvents.js';
import { RegionDB, REGIONS } from './data/regions.js';
import { createLandmarkData } from './world/landmarks.js';
import { Codex } from './quests/codex.js';
import { Dialogue } from './cinematic/dialogue.js';
import { PlayerProfile } from './ui/profile.js';
import { ObjectPool } from './performance/objectPool.js';
import { NPCS, npcActivity } from './data/npcs.js';
import { Shop } from './economy/shop.js';
import { Reputation } from './economy/reputation.js';
import { MissionCargoManager } from './quests/deliveryCargo.js';
import { hotbar, selectHotbar, renderHotbar, hotbarFromJSON, hotbarToJSON, selectedItem } from './ui/hotbar.js';

const TAU=Math.PI*2;
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const hash=(x,z,seed=0)=>{const n=Math.sin(x*127.1+z*311.7+seed*74.7)*43758.5453;return n-Math.floor(n)};
const cssColor=value=>typeof value==='number'?`#${value.toString(16).padStart(6,'0')}`:value;
const makeTransform=()=>({rotation:{x:0,y:0,z:0},position:{x:0,y:0,z:0,set(x,y,z){this.x=x;this.y=y;this.z=z}},scale:{x:1,y:1,z:1,set(x,y,z){this.x=x;this.y=y;this.z=z},setScalar(value){this.x=this.y=this.z=value}},visible:true});
const RESOURCE_COLORS={tree:'#335f2d',rock:'#77766f',coal:'#1f2021',iron_ore:'#a8542e',copper_ore:'#b96b3e',crystal:'#76ccea',titanium_ore:'#697bc0',ember_core:'#e34827',scrap:'#776d62',herbs:'#3c8a55'};
const REGION_TINTS={plain:'rgba(70,106,51,.16)',forest:'rgba(8,52,28,.52)',mountain:'rgba(71,79,83,.58)',city:'rgba(76,68,62,.58)',desert:'rgba(177,133,70,.64)',snow:'rgba(195,215,225,.67)',volcano:'rgba(72,24,18,.7)',zero:'rgba(20,36,52,.72)'};

export class Game{
  constructor(canvas){
    this.canvas=canvas;
    this.ctx=canvas.getContext('2d',{alpha:false});
    if(!this.ctx)throw new Error('Canvas 2D indisponível');
    this.width=innerWidth;this.height=innerHeight;this.pixelRatio=1;this.running=false;this.lastFrame=performance.now();this.fps=0;this.elapsed=0;
    this.camera={x:0,z:0,zoom:34};
    this.scene={type:'Canvas2DScene'};
    this.renderer={render:()=>this.draw(),setPixelRatio:value=>{this.pixelRatio=value;this.onResize()},setSize:()=>this.onResize(),shadowMap:{enabled:false}};
    this.clock={getDelta:()=>{const now=performance.now(),dt=(now-this.lastFrame)/1000;this.lastFrame=now;return dt}};
    this.player=new Player();this.player.pos.y=.9;
    this.playerState=new PlayerStateMachine(PLAYER_STATES.ON_FOOT);
    this.quests=new QuestManager(this.player,inventory);
    this.cutscene=new CutsceneManager();this.audio=new AudioManager();this.saveMgr=new SaveManager();
    this.equipment=new PlayerEquipment(inventory);this.construction=new ConstructionManager(inventory);this.codex=new Codex();this.dialogue=new Dialogue();this.profile=new PlayerProfile();this.shop=new Shop();this.reputation=new Reputation();
    this.train=new Train({x:0,z:10,wagons:['cargo']});this.trainDamage=new TrainDamage(this.train);this.missionCargo=new MissionCargoManager(this.train);
    this.furnace=new Furnace(output=>{try{inventory.add(output,1);this.quests.record('craft',output,1);showNotif(`🔥 Fundição concluída: +1 ${output}`)}catch{showNotif('Fundição pronta, mas o inventário está cheio.')}});
    this.sword=new Sword();this.pistol=new Pistol();this.weapon='sword';this.furColor='#c49a6c';this.equippedTool=null;
    this.weather='sun';this.timeOfDay='dia';this.dayNight=new DayNight();this.dayNight.time=9;this.weatherSystem=new Weather();
    this.worldStreaming=new WorldStreaming({chunkSize:32,loadRadius:2});this.fogOfWar=new FogOfWar();this.travelEvents=new TravelEventManager();
    this.currentRegion=RegionDB.lookup('plain');this.resources=[];this.stations=[];this.obstacles=[];this.npcs=[];this.enemies=[];this.boss=null;this.remotePlayers=new Map();this.multiplayer=null;
    this.brokenRepaired=false;this.forestLoaded=false;this.transitioning=false;this.checkpoint={x:0,z:0};
    this.trainEnterPoint={x:-.4,y:.9,z:-1.45};this.driverSeat={x:.6,y:.9,z:0};this.trainExitPoint={x:.4,y:.9,z:1.55};
    this.trainPoints={enter:this.trainEnterPoint,driver:this.driverSeat,exit:this.trainExitPoint};
    this.railObj={broken:{visible:true}};this.trainMesh=makeTransform();this.playerMesh=makeTransform();this.playerMesh.children=[];
    const animRoot=makeTransform(),body=makeTransform(),head=makeTransform(),rightHand=makeTransform(),legs=Array.from({length:4},makeTransform);
    this.playerAnimator=new PlayerAnimator(animRoot,{body,head,rightHand,legs});
    this.keys={};this.mouse={x:innerWidth/2,y:innerHeight/2,worldX:1,worldZ:0};this.facing=0;this.jumpVelocity=0;this.grounded=true;this._paused=false;this._menuResumeState=null;this._combatTimer=0;
    this.settings={controls:{forward:'w',back:'s',left:'a',right:'d',interact:'e',sprint:'shift',jump:' '},cameraShake:100,vegetation:100,particles:true,resolution:1};
    this.particlePool=new ObjectPool(()=>({active:false,x:0,z:0,vx:0,vz:0,life:0,size:.12,color:'#e2bf77'}),{initial:30,reset:(item,data,active)=>{item.active=active;if(data)Object.assign(item,data)}});
    this.projectilePool=new ObjectPool(()=>({active:false,x:0,z:0,vx:0,vz:0,life:0,size:.08,color:'#ffe19a'}),{initial:12,reset:(item,data,active)=>{item.active=active;if(data)Object.assign(item,data)}});
    this.mobPool=new ObjectPool(()=>({active:false,x:0,z:0}),{initial:8,reset:(item,data,active)=>{item.active=active;if(data)Object.assign(item,data)}});
    this.assets={};this.patterns={};this.decor=[];this._hudTimer=0;this._streamTimer=0;this._worldTimer=0;this._saveCd=12;this.networkTimer=0;this._lastObjectiveText='';
    this.init();
  }

  get state(){return this.playerState.state}
  setFurColor(color){this.furColor=color||'#c49a6c'}
  transitionPlayer(nextState,context={}){const changed=this.playerState.transition(nextState,context);if(changed){this._paused=this.playerState.isPaused;if(this._paused)this.keys={}}return changed}
  beginMenu(){if(this.playerState.is(PLAYER_STATES.DEAD,PLAYER_STATES.CUTSCENE))return false;if(!this.playerState.is(PLAYER_STATES.MENU)){this._menuResumeState=this.state;return this.transitionPlayer(PLAYER_STATES.MENU,{reason:'overlay'})}return true}
  closeMenu(){document.querySelectorAll('.overlay').forEach(item=>item.classList.remove('active'));if(!this.playerState.is(PLAYER_STATES.MENU))return false;const resume=this._menuResumeState||(this.train.inTrain?PLAYER_STATES.IN_TRAIN:PLAYER_STATES.ON_FOOT);this._menuResumeState=null;return this.transitionPlayer(resume,{reason:'close-overlay'})}
  playCutscene(id,onDone){if(this.playerState.is(PLAYER_STATES.DEAD,PLAYER_STATES.CUTSCENE))return false;const resume=this.state;if(!this.transitionPlayer(PLAYER_STATES.CUTSCENE,{id}))return false;this.cutscene.play(id,reason=>{if(this.playerState.is(PLAYER_STATES.CUTSCENE))this.transitionPlayer(resume,{reason});onDone?.(reason)});return true}
  skipCutscene(){this.cutscene.skip()}
  enterTrain(){if(this.playerState.is(PLAYER_STATES.COMBAT))this.transitionPlayer(PLAYER_STATES.ON_FOOT,{reason:'enter-train'});if(!this.transitionPlayer(PLAYER_STATES.ENTERING_TRAIN))return false;this.train.inTrain=true;this.player.pos={...this.getTrainPoint('driver')};this.transitionPlayer(PLAYER_STATES.IN_TRAIN);return true}
  exitTrain(){if(!this.playerState.is(PLAYER_STATES.IN_TRAIN,PLAYER_STATES.DRIVING))return false;this.train.inTrain=false;this.train.speed=0;this.train.throttle=0;this.player.pos={...this.getTrainPoint('exit')};this.transitionPlayer(PLAYER_STATES.ON_FOOT);showNotif('Saiu do trem');return true}
  respawn(position={x:0,z:0}){if(!this.playerState.is(PLAYER_STATES.DEAD))return false;this.player.health.current=this.player.health.max;this.player.pos={x:position.x,y:.9,z:position.z};this.train.inTrain=false;this.train.speed=0;this.keys={};const screen=document.getElementById('death-screen');if(screen)screen.style.display='none';this.transitionPlayer(PLAYER_STATES.ON_FOOT,{reason:'respawn'});this.playerAnimator.update(0,{playerState:PLAYER_STATES.ON_FOOT,grounded:true});return true}
  damagePlayer(amount){const previous=this.player.health.current;this.player.health.damage(this.sword.mitigate(amount));if(this.player.health.current<previous){this.playerAnimator.play(PLAYER_ANIMATIONS.HURT);this.cameraShakeOffset=(this.settings.cameraShake||0)/100*.18}return previous-this.player.health.current}
  getPlayerColliders(){const colliders=[...this.obstacles];if(!this.train.inTrain)colliders.push({x:this.train.x,z:this.train.z,radius:1.45});for(const node of this.resources)if(!node.depleted)colliders.push({x:node.x,z:node.z,radius:node.type==='tree'?.58:.42});for(const station of this.stations)colliders.push({x:station.x,z:station.z,radius:.72});for(const npc of this.npcs)colliders.push({x:npc.x,z:npc.z,radius:.32});return colliders}
  getTrainPoint(name){const point=this.trainPoints[name]||{x:0,y:.9,z:0};return{x:this.train.x+point.x,y:point.y||.9,z:this.train.z+point.z}}
  useItem(id=selectedItem()){const result=consumeItem(inventory,id,this.player);showNotif(result.ok?`Usou ${id}`:result.reason);return result}
  openNpc(npc){if(!this.beginMenu())return false;this.currentNpc=npc;const name=document.getElementById('npc-name'),text=document.getElementById('npc-dialogue'),panel=document.getElementById('npc-panel');if(name)name.textContent=npc.name;if(text)text.textContent=`${npc.dialogueText} • Rotina: ${npc.activity||'trabalho'} • Reputação ${this.reputation.level(npc.reputation||this.currentRegion.id)}`;panel?.classList.add('active');this.dialogue.show(npc.name,npc.dialogueText);this.codex.discover(`npc:${npc.id}`,{type:'npc',name:npc.name});return true}
  buyFromNpc(){if(!this.currentNpc)return false;const faction=this.currentNpc.reputation||this.currentRegion.id,result=this.shop.buy('bread',1,this.player,inventory,{region:this.currentRegion.id,reputation:this.reputation.level(faction)});showNotif(result.ok?`Pão comprado por ${result.cost} moedas`:result.reason);if(result.ok)this.reputation.add(faction,2);return result.ok}
  craftingContext(){return{completedQuests:this.quests.quests.filter(quest=>quest.completed).map(quest=>quest.id),discoveries:[...this.codex.discoveries],technologies:this.player.technologies||[],reputation:Object.fromEntries(RegionDB.all().map(region=>[region.id,this.reputation.level(region.id)]))}}
  attachWagon(itemId){const item=inventory.item(itemId);if(!item?.wagonType||!inventory.remove(itemId,1))return false;const wagon=this.train.attach(item.wagonType);this.createWagonMesh(wagon,this.train.wagons.length-1);showNotif(`${wagon.name} acoplado`);return true}

  loadAsset(name,path){const image=new Image();image.onload=()=>{this.assets[name]=image;if(name==='grass')this.patterns.grass=this.ctx.createPattern(image,'repeat')};image.onerror=()=>{this.assets[name]=null};image.src=`${import.meta.env.BASE_URL||'/'}${path}`}
  createNode(data){const definition=resourceDefinition(data.type)||{tool:data.type==='tree'||data.type==='herbs'?'axe':'pick',tier:0,hp:2,drops:[{item:data.type,amount:1,chance:1}]};const node=new ResourceNode({...data,...definition});node.mesh=makeTransform();return node}
  initWorld(){
    this.regionalWorld={groups:new Map(),landmarks:[],resources:[]};
    for(const region of REGIONS){for(let index=0;index<region.landmarks.length;index++){const landmark=createLandmarkData(region,index);this.regionalWorld.landmarks.push(landmark);this.fogOfWar.addMarker(landmark.id,{x:landmark.x,z:landmark.z,type:'landmark',name:landmark.type})}region.resources.slice(0,4).forEach((raw,index)=>{const type=raw==='wood'?'tree':raw==='stone'?'rock':raw,x=region.center.x-17+index*10,z=index%2?23:-23;const node=this.createNode({id:`${region.id}:resource:${index}`,type,x,z});this.regionalWorld.resources.push(node);this.resources.push(node)})}
    const starter=[['tree',8,-6],['tree',12,-8],['tree',-10,8],['rock',6,4],['rock',14,-2],['coal',11,7],['coal',-8,-4],['coal',-4,6],['iron_ore',16,5],['iron_ore',-12,-6],['scrap',9,9],['scrap',-6,-10],['herbs',4,-12]];
    starter.forEach(([type,x,z],index)=>this.resources.push(this.createNode({id:`starter-${index}`,type,x,z})));
    this.obstacles.push({x:2,z:12,radius:2.2});
    this.npcs=NPCS.map(data=>({...data,x:data.position.x,z:data.position.z,dialogueText:data.id==='mechanic'?'Os trilhos do norte ainda podem ser reparados. Recolha sucata e lingotes para recuperar a locomotiva.':`${data.name} oferece suprimentos e novas rotas.`,activity:'idle',mesh:makeTransform()}));
    for(let x=-55;x<480;x+=3.5)for(let z=-48;z<49;z+=3.5){const value=hash(x,z);if(value>.82)this.decor.push({x:x+(hash(x,z,2)-.5)*2,z:z+(hash(x,z,3)-.5)*2,type:value>.94?'stone':'grass',size:.3+hash(x,z,4)*.55})}
    this.worldStreaming.createChunk=chunk=>({objects:this.resources.filter(item=>Math.floor(item.x/32)===chunk.cx&&Math.floor(item.z/32)===chunk.cz)});
    this.worldStreaming.onLoad=chunk=>chunk.objects.forEach(item=>item.mesh.visible=true);this.worldStreaming.onUnload=chunk=>chunk.objects.forEach(item=>item.mesh.visible=false);
  }
  init(){
    this.loadAsset('capybara','assets/sprites/capybara-realistic.webp');this.loadAsset('locomotive','assets/sprites/locomotive-realistic.webp');this.loadAsset('tree','assets/sprites/tree-realistic.webp');this.loadAsset('rock','assets/sprites/rock-realistic.webp');this.loadAsset('grass','assets/textures/grass-realistic.webp');
    this.initWorld();this.onResize();
    this._onKeyDown=event=>this.onKey(event,true);this._onKeyUp=event=>this.onKey(event,false);this._onResize=()=>this.onResize();
    addEventListener('keydown',this._onKeyDown);addEventListener('keyup',this._onKeyUp);addEventListener('resize',this._onResize);
    this.canvas.addEventListener('mousemove',event=>{const rect=this.canvas.getBoundingClientRect();this.mouse.x=event.clientX-rect.left;this.mouse.y=event.clientY-rect.top;const world=this.screenToWorld(this.mouse.x,this.mouse.y);this.mouse.worldX=world.x;this.mouse.worldZ=world.z;this.facing=Math.atan2(world.z-this.player.pos.z,world.x-this.player.pos.x)});
    this.canvas.addEventListener('mousedown',event=>{if(event.button===0)this.onShoot({heavy:this.keys.shift});if(event.button===2&&this.weapon==='sword')this.sword.setBlocking(true)});this.canvas.addEventListener('mouseup',event=>{if(event.button===2)this.sword.setBlocking(false)});this.canvas.addEventListener('contextmenu',event=>event.preventDefault());
    this.canvas.addEventListener('wheel',event=>{if(event.ctrlKey){this.setCameraDistance(this.cameraDistance+event.deltaY*.01);event.preventDefault();return}const step=event.deltaY>0?1:-1;selectHotbar((hotbar.selected+step+hotbar.slots.length)%hotbar.slots.length);event.preventDefault()},{passive:false});
    inventory.onChange(()=>{renderInventory();this.updateQuestHUD()});inventory.onChange(renderHotbar);renderRecipes('hand',this.player.level);this.updateQuestHUD();
    const saved=this.saveMgr.load();if(saved){this.applySave(saved);showNotif('Save carregado')}else{for(const [id,amount]of[['axe_wood',1],['pick_wood',1],['sword_iron',1],['pistol_basic',1],['ammo_pistol',36],['bread',2]])inventory.add(id,amount)}
    const continueButton=document.getElementById('btn-continuar');if(this.saveMgr.has()&&continueButton)continueButton.disabled=false;
    addEventListener('keydown',event=>{if(!import.meta.env.DEV&&event.key!=='F1')return;if(event.key==='F1'){event.preventDefault();showNotif(`FPS: ${this.fps} • Canvas 2D`)}if(event.key==='F2'){event.preventDefault();showNotif(`Posição: ${this.player.pos.x.toFixed(1)}, ${this.player.pos.z.toFixed(1)}`)}if(event.key==='F3'){event.preventDefault();showNotif(`Trem: ${this.train.speed.toFixed(1)} km/h • combustível ${Math.round(this.train.fuel)}%`)}if(event.key==='F4'){event.preventDefault();this.player.pos={x:12,y:.9,z:10};showNotif('F4: teleporte para o trilho quebrado')}if(event.key==='F5'){event.preventDefault();['wood','stone','coal','iron_ore','iron_ingot','scrap'].forEach(id=>inventory.add(id,5));showNotif('F5 +recursos')}if(event.key==='F6'){this.player.coins+=500;showNotif('F6 +500 coins')}if(event.key==='F7'){const quest=this.quests.active();if(quest){quest.objectives.forEach(objective=>objective.done=true);this.quests.checkComplete(quest)}}if(event.key==='F8'){this.weatherSystem.set(this.weather==='fog'?'sun':'fog');showNotif(`F8: clima ${this.weatherSystem.state.type}`)}if(event.key==='F9'){this.dayNight.time=this.timeOfDay==='noite'?9:22;showNotif(`F9: ${this.dayNight.phase()}`)}});
  }

  createWagonMesh(wagon,index){return{wagon,index}}
  spawnEnemies(){
    this.enemies=[];const spots=this.forestLoaded?[[22,6],[28,-5],[34,12],[25,-13],[39,8]]:[[6,6],[-8,5],[14,14],[-14,-8],[10,-12]];
    for(const [index,[x,z]]of spots.entries()){const mob=spawnMob(this.forestLoaded?(index%2===0?'spore':'wolf'):(index%2===0?'slime':'boar'),x,z);if(mob){mob.ai=new EnemyAI(mob);this.enemies.push(mob)}}
    if(this.forestLoaded){const eliteData=ENEMIES.find(enemy=>enemy.id==='elite_boar');if(eliteData){const elite=new Elite({...eliteData,x:31,z:15});elite.ai=new EnemyAI(elite);this.enemies.push(elite);const mini=new MiniBoss({...eliteData,id:'forest_brute',name:'Bruto da Ruína',loot:'elite_loot',xp:160,x:37,z:-11});mini.ai=new EnemyAI(mini);this.enemies.push(mini)}}
    const quest=this.quests.quests.find(item=>item.id==='guardian_forest');if(quest?.active&&!quest.completed){this.boss=new Boss('forest_guardian');this.boss.ai=new EnemyAI(this.boss);this.audio.play(this.boss.music,{channel:'music'});this.playCutscene(`Entrada de chefe — ${this.boss.name}`,()=>{})}
  }
  onKey(event,down){
    const raw=event.key.toLowerCase(),bindings=this.settings.controls||{},key=Object.entries(bindings).find(([,bound])=>bound===raw)?.[0]||raw;
    if(!down){this.keys[key]=false;return}if(this.playerState.is(PLAYER_STATES.DEAD,PLAYER_STATES.CUTSCENE))return;if(event.key==='Escape'){this.togglePause();return}
    if(this.playerState.is(PLAYER_STATES.MENU)){if(key==='i')this.toggle('inventory-panel');else if(key==='m')this.toggle('map-panel');else if(key==='j')this.toggle('quests-panel');return}
    this.keys[key]=true;if(/^[1-9]$/.test(event.key)){selectHotbar(Number(event.key)-1);return}if(key==='i'){this.toggle('inventory-panel');return}if(key==='m'){this.toggle('map-panel');return}if(key==='j'){this.toggle('quests-panel');return}if((key==='interact'||key==='e')&&this.playerState.is(PLAYER_STATES.IN_TRAIN,PLAYER_STATES.DRIVING)){this.train.brake(.5);return}if(key==='interact'||key==='e'){this.tryInteract();return}if(key==='q'&&this.playerState.is(PLAYER_STATES.IN_TRAIN,PLAYER_STATES.DRIVING)){this.accelerate();return}if(key==='r'&&this.weapon!=='pistol'){this.tryRepair();return}if(key==='f'&&this.exitTrain())return;if(key==='r'&&this.weapon==='pistol'){if(this.pistol.reload()){showNotif(`Recarregando por ${this.pistol.reloadDuration.toFixed(1)}s…`);this.audio.play('pistol_reload',{channel:'effects'})}else showNotif('Não é possível recarregar agora');return}if(key==='h'&&this.train.inTrain)showNotif('🚂 BUZINA! Piiiii!');if(key==='b')this.placeStation();
    if((key==='jump'||event.code==='Space')&&inventory.item(selectedItem())?.category==='consumable'&&!this.train.inTrain){this.useItem(selectedItem());return}if((key==='jump'||event.code==='Space')&&this.playerState.is(PLAYER_STATES.DRIVING)){this.train.speed*=.15;showNotif('🛑 Freio de emergência');return}if((key==='jump'||event.code==='Space')&&this.grounded&&this.playerState.canMove){this.jumpVelocity=6.5;this.grounded=false;this.audio.play('jump',{channel:'effects'})}
  }
  equipWeapon(weapon){if(!['sword','pistol'].includes(weapon))return;this.weapon=weapon;this.equippedTool=null;this.equipment.equip(weapon==='sword'?'sword_iron':'pistol_basic');showNotif(weapon==='sword'?'Espada equipada':'Pistola equipada')}
  equipTool(id){if(['sword_iron','pistol_basic'].includes(id))return;this.equippedTool=id;this.equipment.equip(id)}
  createStation(type,x,z,starter=false,id=null){const station={id:id||`station-${type}-${this.stations.length}`,type,x,z,starter};this.stations.push(station);return station}
  placeStation(){if(this.train.inTrain)return;if(this.keys.alt){const nearest=this.stations.filter(station=>!station.starter).sort((a,b)=>distance(a,this.player.pos)-distance(b,this.player.pos))[0];if(nearest&&distance(nearest,this.player.pos)<3){const removed=this.construction.remove(nearest.id);if(removed.ok){this.stations=this.stations.filter(station=>station!==nearest);showNotif('Estrutura removida e devolvida ao inventário')}return}}const type=['crafting_table','furnace','chest','workshop','engineering_table','laboratory'].find(id=>inventory.has(id));if(!type){showNotif('Crie uma Mesa de Crafting ou Fornalha primeiro.');return}const placed=this.construction.place(type,{x:this.player.pos.x+Math.cos(this.facing)*2,z:this.player.pos.z+Math.sin(this.facing)*2});if(!placed.ok){showNotif(placed.reason);return}this.createStation(type,placed.structure.x,placed.structure.z,false,placed.structure.id);showNotif(`${type==='crafting_table'?'Mesa de Crafting':'Fornalha'} posicionada.`)}
  openCrafting(station){if(!this.beginMenu())return;document.querySelectorAll('.overlay').forEach(item=>item.classList.remove('active'));if(station==='furnace')document.getElementById('furnace-panel')?.classList.add('active');else{document.getElementById('crafting-panel')?.classList.add('active');const title=document.getElementById('crafting-title');if(title)title.textContent=station.replaceAll('_',' ').toUpperCase();renderRecipes(station,this.player.level)}}
  nearestEnemy(maxDistance=Infinity){let best=null,bestDistance=maxDistance;for(const enemy of [...this.enemies,this.boss].filter(Boolean)){if(enemy.state==='DEAD')continue;const value=distance(enemy,this.player.pos);if(value<bestDistance){best=enemy;bestDistance=value}}return best}
  onShoot({heavy=false}={}){
    if(!this.playerState.canCombat)return;if(this.playerState.is(PLAYER_STATES.ON_FOOT))this.transitionPlayer(PLAYER_STATES.COMBAT,{weapon:this.weapon});this._combatTimer=this.weapon==='sword'?.4:.25;
    if(this.weapon==='sword'){const attack=this.sword.attack(performance.now()/1000,{heavy});if(!attack.ok){showNotif(attack.reason);return}if(!this.player.stamina.use(attack.stamina)){showNotif('Sem stamina!');return}inventory.damageDurability('sword_iron',heavy?2:1);this.playerAnimator.play(PLAYER_ANIMATIONS.ATTACK);const hit=this.nearestEnemy(2.5);if(hit){const damageValue=calcDamage(attack.damage,hit.defense||2);hit.takeDamage(damageValue,{stun:heavy?.35:0});showNotif(`-${damageValue} ${hit.name}`);if(hit.state==='DEAD')this.onKill(hit)}else showNotif(heavy?'Ataque pesado!':`Golpe! combo ${attack.combo}`)}
    else{const shot=this.pistol.shoot();if(!shot.ok){showNotif(shot.reason);return}this.audio.play('pistol_shot',{channel:'effects'});this.playerAnimator.play(PLAYER_ANIMATIONS.ATTACK);const direction={x:Math.cos(this.facing),z:Math.sin(this.facing)};const projectile=this.projectilePool.acquire({x:this.player.pos.x,z:this.player.pos.z,vx:direction.x*34,vz:direction.z*34,life:.32});let hit=null,along=Infinity;for(const enemy of [...this.enemies,this.boss].filter(Boolean)){if(enemy.state==='DEAD')continue;const dx=enemy.x-this.player.pos.x,dz=enemy.z-this.player.pos.z,projection=dx*direction.x+dz*direction.z,side=Math.abs(dx*direction.z-dz*direction.x);if(projection>0&&projection<shot.range&&side<.75&&projection<along){hit=enemy;along=projection}}if(hit){const damageValue=calcDamage(25,hit.defense||2);hit.takeDamage(damageValue);this.audio.play('pistol_hit',{channel:'effects'});showNotif(`🔫 -${damageValue} ${hit.name}`);if(hit.state==='DEAD')this.onKill(hit)}else showNotif(`🔫 Bang! ${this.pistol.mag}/${this.pistol.magSize}`);setTimeout(()=>this.projectilePool.release(projectile),350)}
  }
  onKill(enemy){const loot=rollLoot(enemy.loot||'slime_loot');for(const item of loot)try{inventory.add(item.id,item.amount);showNotif(`+${item.amount} ${item.id}`)}catch{}this.player.addXP(enemy.xp||12);this.player.coins+=10;this.profile.add('enemiesDefeated');this.profile.collect('enemies',enemy.baseId||enemy.id);this.quests.record('kill',enemy.baseId||enemy.id,1);showNotif(`+${enemy.xp||12} XP`);if(enemy.boss){this.profile.add('bossesDefeated');this.audio.play(enemy.music||'boss_victory',{channel:'music'});this.playCutscene('Vitória! Guardião derrotado',()=>{showNotif(`🎉 ${enemy.name} derrotado!`);const bar=document.getElementById('boss-bar');if(bar)bar.style.display='none'})}}
  tryInteract(){
    if(this.exitTrain())return;if(!this.playerState.is(PLAYER_STATES.ON_FOOT,PLAYER_STATES.COMBAT))return;this.playerAnimator.play(PLAYER_ANIMATIONS.INTERACT);
    if(distance(this.player.pos,this.train)<2.6){const quest=this.quests.quests.find(item=>item.id==='first_departure');if(quest&&!quest.objectives[0].done){this.quests.record('interact','train');showNotif('Locomotiva inspecionada')}if(inventory.count('coal')>=3&&quest&&!quest.objectives[1].done){inventory.remove('coal',3);this.train.fuel=Math.min(100,this.train.fuel+30);this.quests.record('collect','coal',3);showNotif('Abastecido +30%')}else if(inventory.count('coal')>=1){inventory.remove('coal',1);this.train.fuel=Math.min(100,this.train.fuel+10);showNotif('⛽ +10%')}this.enterTrain();this.quests.record('interact','enter');showNotif('Entrou na cabine — Q acelera, E freia, F sai');return}
    for(const station of this.stations)if(distance(station,this.player.pos)<2.25){this.openCrafting(station.type);return}
    for(const npc of this.npcs)if(distance(npc,this.player.pos)<2.3){this.openNpc(npc);showNotif('Novo diálogo registrado no diário');return}
    for(const node of this.resources){if(node.depleted||distance(node,this.player.pos)>=2.2)continue;const toolId=selectedItem(),tool=inventory.item(toolId),toolKind=toolId?.startsWith('axe')?'axe':toolId?.startsWith('pick')?'pick':null,hit=node.hit({tool:toolKind,tier:tool?.tier??-1,power:tool?.efficiency||1});if(!hit.ok){showNotif(hit.reason);return}const durability=inventory.damageDurability(toolId,1);if(durability.broken)showNotif(`${tool.name} quebrou!`);this.audio.play(node.tool==='axe'?'chop':'mine_hit',{channel:'effects'});for(let index=0;index<7;index++)this.particlePool.acquire({x:node.x,z:node.z,vx:(Math.random()-.5)*3,vz:(Math.random()-.5)*3,life:.35+Math.random()*.3,size:.06+Math.random()*.08,color:RESOURCE_COLORS[node.type]||'#d2b57b'});if(hit.depleted){node.mesh.visible=false;for(const drop of hit.drops)try{inventory.add(drop.id,drop.amount);this.quests.record('collect',drop.id,drop.amount);this.profile.collect('resources',drop.id);showNotif(`+${drop.amount} ${drop.id}`)}catch{showNotif('Inventário cheio')}this.profile.add('resourcesMined');setTimeout(()=>{node.respawn();node.mesh.visible=true},node.respawnTime||18000)}else showNotif(`Coletando… ${Math.ceil(node.hp)}/${node.maxHp}`);return}
    showNotif('Nada para interagir');
  }
  advanceObjective(type,target,amount=1){return this.quests.record(type,target,amount)}
  chooseTravelEvent(choice){const result=this.travelEvents.choose(choice,{inventory,train:this.train});if(result.ok){document.getElementById('travel-event')?.classList.remove('active');if(this.playerState.is(PLAYER_STATES.MENU))this.closeMenu();showNotif(`Evento resolvido: ${result.result}`);this.quests.record('choice',result.result,1)}else showNotif(result.reason);return result}
  showTransition(title,subtitle,hint,onDone){if(this.transitioning)return;this.transitioning=true;const panel=document.getElementById('transition'),bar=document.getElementById('transition-bar'),titleNode=document.getElementById('transition-title'),subtitleNode=document.getElementById('transition-subtitle'),hintNode=document.getElementById('transition-hint');if(titleNode)titleNode.textContent=title;if(subtitleNode)subtitleNode.textContent=subtitle;if(hintNode)hintNode.textContent=hint;panel?.classList.add('active');let progress=0;const timer=setInterval(()=>{progress=Math.min(100,progress+Math.random()*18+8);if(bar)bar.style.width=`${progress}%`;if(progress>=100){clearInterval(timer);setTimeout(()=>{panel?.classList.remove('active');if(bar)bar.style.width='0%';this.transitioning=false;onDone?.()},420)}},140)}
  loadForest(){if(this.forestLoaded)return;this.forestLoaded=true;const extras=[['iron_ore',26,6],['iron_ore',30,-8],['crystal',32,4],['coal',28,10],['scrap',24,-12],['herbs',27,-5]];extras.forEach(([type,x,z],index)=>this.resources.push(this.createNode({id:`forest-${index}`,type,x,z})));for(let index=0;index<18;index++)this.obstacles.push({x:22+Math.random()*28,z:(Math.random()-.5)*34,radius:.7,tree:true});this.spawnEnemies();const quest=this.quests.quests.find(item=>item.id==='forest_threat');if(quest&&!quest.active&&!quest.completed){quest.active=true;showNotif('Nova missão: Ameaça da Floresta')}}
  tryRepair(){if(this.brokenRepaired)return;if(Math.hypot(14-this.player.pos.x,10-this.player.pos.z)<3){if(inventory.count('scrap')>=3&&inventory.count('iron_ingot')>=2){inventory.remove('scrap',3);inventory.remove('iron_ingot',2);this.brokenRepaired=true;this.railObj.broken.visible=false;this.profile.add('railsRepaired');showNotif('Trilho reparado! Preparando travessia…');this.showTransition('Carregando Floresta…','Trilho restaurado • 18km à frente','Esporos venenosos são fracos contra fogo',()=>{this.loadForest();this.player.pos={x:18.5,y:.9,z:10};this.doSave(true)})}else showNotif('Precisa 3 sucata +2 lingotes')}}
  accelerate(){if(this.train.fuel<=0){showNotif('Sem combustível!');return}this.train.accelerate(.35);const quest=this.quests.quests.find(item=>item.id==='first_departure');if(quest&&!quest.objectives[3].done){this.quests.record('travel','depart');showNotif('Partiu! 🚂')}}
  toggle(name){const panel=document.getElementById(name);if(!panel)return;const open=panel.classList.contains('active');document.querySelectorAll('.overlay').forEach(item=>item.classList.remove('active'));if(open)this.closeMenu();else if(this.beginMenu())panel.classList.add('active');if(name==='inventory-panel')renderInventory();if(name==='quests-panel')this.renderQuests();if(name==='map-panel')this.renderMap();if(name==='profile-panel')this.renderProfile()}
  togglePause(){const panel=document.getElementById('pause-menu');if(this.playerState.is(PLAYER_STATES.MENU)){this.closeMenu();return}if(this.beginMenu())panel?.classList.add('active')}
  renderQuests(){const list=document.getElementById('quest-list');if(!list)return;list.innerHTML='';for(const quest of this.quests.quests){const card=document.createElement('div');card.className='quest-card';card.innerHTML=`<b>${quest.completed?'✓ ':''}${quest.name}</b><br>${quest.objectives.map(objective=>`${objective.done?'☑':'☐'} ${objective.description}${objective.amount>1?` (${objective.progress||0}/${objective.amount})`:''}`).join('<br>')}`;list.appendChild(card)}}
  renderMap(){const canvas=document.getElementById('map-canvas');if(!canvas)return;const ctx=canvas.getContext('2d'),width=canvas.width,height=canvas.height;ctx.fillStyle='#102018';ctx.fillRect(0,0,width,height);for(const region of REGIONS){const x=(region.bounds[0]+50)/520*width,w=(region.bounds[1]-region.bounds[0])/520*width;ctx.fillStyle=cssColor(region.color);ctx.globalAlpha=.72;ctx.fillRect(x,20,w,height-40);ctx.globalAlpha=1;ctx.fillStyle='#f4e9c6';ctx.font='9px sans-serif';ctx.fillText(region.name,x+3,16)}ctx.strokeStyle='#c3aa70';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,height*.55);ctx.lineTo(width,height*.55);ctx.stroke();for(const marker of this.fogOfWar.visibleMarkers()){ctx.fillStyle='#f4d56b';ctx.beginPath();ctx.arc((marker.x+50)/520*width,height*.55+marker.z/90*height,2.5,0,TAU);ctx.fill()}ctx.fillStyle='#fff';ctx.beginPath();ctx.arc((this.player.pos.x+50)/520*width,height*.55+this.player.pos.z/90*height,4,0,TAU);ctx.fill()}
  renderProfile(){const panel=document.getElementById('profile-content');if(panel)panel.innerHTML=`<b>Nível ${this.player.level}</b> • ${this.player.xp}/100 XP<br>Tempo: ${Math.floor(this.profile.stats.playTime||0)}s<br>Inimigos: ${this.profile.stats.enemiesDefeated||0}<br>Recursos: ${this.profile.stats.resourcesMined||0}<br>Regiões: ${this.profile.collections.regions.size}/${REGIONS.length}<hr>Codex: ${this.codex.discoveries.size} descobertas`}
  renderObjective(){const element=document.getElementById('objective-tracker');if(!element)return;const quest=this.quests.active();if(!quest){if(this._lastObjectiveText!=='Nenhum objetivo ativo'){element.textContent='Nenhum objetivo ativo';this._lastObjectiveText='Nenhum objetivo ativo'}return}const next=quest.objectives.find(objective=>!objective.done),text=`<b>${quest.name}</b><br>${next?`▸ ${next.description}${next.amount>1?` (${next.progress||0}/${next.amount})`:''}`:'✓ Objetivos concluídos'}`;if(text!==this._lastObjectiveText){element.innerHTML=text;this._lastObjectiveText=text}}
  updateQuestHUD(){}
  applySave(data){try{if(data.inventory)inventory.fromJSON(data.inventory);if(data.player){this.player.level=Number.isFinite(data.player.level)?data.player.level:1;this.player.xp=Number.isFinite(data.player.xp)?data.player.xp:0;this.player.coins=Number.isFinite(data.player.coins)?data.player.coins:100;if(data.player.pos&&Number.isFinite(data.player.pos.x)&&Number.isFinite(data.player.pos.z))this.player.pos={x:data.player.pos.x,y:.9,z:data.player.pos.z};if(data.player.train){this.train.fromJSON(data.player.train);if(this.train.inTrain){this.transitionPlayer(PLAYER_STATES.ENTERING_TRAIN,{reason:'load-save'});this.transitionPlayer(PLAYER_STATES.IN_TRAIN,{reason:'load-save'})}}}if(data.quests)this.quests.quests=data.quests;hotbarFromJSON(data.hotbar);if(data.world){this.brokenRepaired=!!data.world.brokenRepaired;this.railObj.broken.visible=!this.brokenRepaired;if(data.world.construction){this.construction.fromJSON(data.world.construction);for(const structure of this.construction.placed)this.createStation(structure.type,structure.x,structure.z,false,structure.id)}if(data.world.fog)this.fogOfWar.fromJSON(data.world.fog);if(data.world.codex)this.codex.fromJSON(data.world.codex);if(data.world.dialogue){this.dialogue.history=data.world.dialogue.history||[];this.dialogue.flags=data.world.dialogue.flags||{}}if(data.world.forestLoaded)this.loadForest()}if(data.profile)this.profile.fromJSON(data.profile);if(data.reputation)this.reputation.fromJSON(data.reputation);if(data.missionCargo)this.missionCargo.fromJSON(data.missionCargo)}catch{}}
  onResize(){const rect=this.canvas.getBoundingClientRect(),width=rect.width||innerWidth,height=rect.height||innerHeight,ratio=Math.min(2,(devicePixelRatio||1)*(Number(this.settings.resolution)||1));this.width=width;this.height=height;this.pixelRatio=ratio;this.canvas.width=Math.max(1,Math.floor(width*ratio));this.canvas.height=Math.max(1,Math.floor(height*ratio));this.ctx.setTransform(ratio,0,0,ratio,0,0);if(this.assets.grass)this.patterns.grass=this.ctx.createPattern(this.assets.grass,'repeat')}
  setQuality(quality){this.settings.quality=quality;this.onResize()}
  applySettings(settings={}){this.settings={...this.settings,...settings,controls:{...this.settings.controls,...(settings.controls||{})}};this.cameraDistance=Number(settings.cameraDistance)||9;this.camera.zoom=clamp(320/this.cameraDistance,22,54);this.worldStreaming.setLoadRadius(settings.viewDistance||2);for(const channel of ['music','effects','ambient','interface'])this.audio.setVolume((settings[channel]??80)/100,channel);this.audio.setVolume((settings.volume??80)/100,'master');this.onResize();if(settings.fullscreen&&!document.fullscreenElement)this.canvas.requestFullscreen?.().catch(()=>{});else if(!settings.fullscreen&&document.fullscreenElement)document.exitFullscreen?.().catch(()=>{})}
  setCameraDistance(distance,persist=true){this.cameraDistance=clamp(Number(distance)||9,4,16);this.camera.zoom=clamp(320/this.cameraDistance,22,54);if(persist)try{const settings=JSON.parse(localStorage.getItem('carpincho_settings')||'{}');settings.cameraDistance=this.cameraDistance;localStorage.setItem('carpincho_settings',JSON.stringify(settings))}catch{}}
  attachMultiplayer(multiplayer){this.multiplayer=multiplayer;document.getElementById('chat')?.classList.add('active');multiplayer.onMessage(message=>{if(message.type==='PLAYER_STATE'&&message.payload.playerId!==multiplayer.playerId){const state=message.payload,remote=this.remotePlayers.get(state.playerId)||{x:state.x,z:state.z,targetX:state.x,targetZ:state.z,facing:0};remote.targetX=state.x;remote.targetZ=state.z;remote.facing=state.yaw||0;this.remotePlayers.set(state.playerId,remote)}else if(message.type==='TRAIN_STATE'&&!multiplayer.isHost)this.train.fromJSON({...this.train.toJSON(),...message.payload});else if(message.type==='WORLD_STATE'&&!multiplayer.isHost)for(const state of message.payload.mobs||[]){const enemy=this.enemies.find(item=>(item.baseId||item.id)===state.id);if(enemy)Object.assign(enemy,state)}else if(message.type==='CHAT'){const log=document.getElementById('chat-log');if(log){const line=document.createElement('div');line.textContent=`${message.payload.from}: ${message.payload.text}`;log.appendChild(line);log.scrollTop=log.scrollHeight}}else if(message.type==='PLAYER_LEFT')this.remotePlayers.delete(message.payload.playerId)})}

  update(dt){
    this.elapsed+=dt;this._streamTimer-=dt;if(this._streamTimer<=0){this._streamTimer=.5;this.worldStreaming.update(this.player.pos);this.fogOfWar.reveal(this.player.pos,1);const region=RegionDB.at(this.player.pos);if(region.id!==this.currentRegion.id){this.currentRegion=region;this.codex.discover(region.id,{type:'region',name:region.name});this.profile.collect('regions',region.id);this.profile.stats.regionsDiscovered=this.profile.collections.regions.size;this.weatherSystem.set(region.climates[0],1);this.quests.record('travel',region.id,1);showNotif(`Região descoberta: ${region.name}`)}for(const landmark of this.regionalWorld.landmarks)if(!landmark.discovered&&distance(landmark,this.player.pos)<5){landmark.discovered=true;this.codex.discover(landmark.id,{type:'landmark',name:landmark.type});this.quests.record('exploration',landmark.type,1);showNotif(`Local descoberto: ${landmark.type}`)}for(const npc of this.npcs)npc.activity=npc.routine?npcActivity(npc,this.dayNight.time):'workshop'}
    this.dayNight.tick(dt);this.timeOfDay=this.dayNight.phase();this.weather=this.weatherSystem.tick(dt).type;if(this.playerState.is(PLAYER_STATES.COMBAT)){this._combatTimer-=dt;if(this._combatTimer<=0)this.transitionPlayer(PLAYER_STATES.ON_FOOT,{reason:'combat-finished'})}
    if(this.playerState.canMove){const wasGrounded=this.grounded;this.jumpVelocity-=18*dt;this.player.pos.y+=this.jumpVelocity*dt;if(this.player.pos.y<=.9){this.player.pos.y=.9;this.jumpVelocity=0;this.grounded=true;if(!wasGrounded)this.playerAnimator.play(PLAYER_ANIMATIONS.LAND)}let dx=0,dz=0;if(this.keys.forward||this.keys.w)dz-=1;if(this.keys.back||this.keys.s)dz+=1;if(this.keys.left||this.keys.a)dx-=1;if(this.keys.right||this.keys.d)dx+=1;let moving=false,sprinting=false;if((dx||dz)&&this.grounded){const length=Math.hypot(dx,dz);dx/=length;dz/=length;moving=true;sprinting=(this.keys.sprint||this.keys.shift)&&this.player.stamina.use(10*dt);const speed=sprinting?6:4;if(!sprinting)this.player.stamina.regen(dt);const next=resolveCircleMovement(this.player.pos,{x:dx*speed*dt,z:dz*speed*dt},this.getPlayerColliders());this.player.pos.x=next.x;this.player.pos.z=next.z;if(Math.hypot(this.mouse.x-this.width/2,this.mouse.y-this.height/2)<20)this.facing=Math.atan2(dz,dx)}else this.player.stamina.regen(dt);if(!this.brokenRepaired&&this.player.pos.x>13.2&&Math.abs(this.player.pos.z-10)<4){this.player.pos.x=13.2;const prompt=document.getElementById('prompt');if(prompt)prompt.textContent='⛔ Trilho quebrado — R com 3 sucata + 2 lingotes'}if(this.brokenRepaired&&!this.forestLoaded&&this.player.pos.x>16.5&&Math.abs(this.player.pos.z-10)<5&&!this.transitioning)this.showTransition('Entrando na Floresta…','Novos recursos e inimigos','O Guardião protege a ruína ao norte',()=>this.loadForest());this.player.pos.x=clamp(this.player.pos.x,-45,465);this.player.pos.z=clamp(this.player.pos.z,-45,45);this.playerAnimator.update(dt,{playerState:this.state,moving,sprinting,grounded:this.grounded})}
    else if(this.playerState.is(PLAYER_STATES.IN_TRAIN,PLAYER_STATES.DRIVING)){if(this.keys.interact||this.keys.e)this.train.brake(.6);this.train.tick(dt,{slope:this.train.x>100&&this.train.x<150?.08:this.train.x>280&&this.train.x<330?-.05:0});if(this.train.speed>.01){if(this.playerState.is(PLAYER_STATES.IN_TRAIN))this.transitionPlayer(PLAYER_STATES.DRIVING);const nextX=this.train.x+this.train.speed*dt*.6;if(!this.brokenRepaired&&nextX>13.2&&Math.abs(this.train.z-10)<3){this.train.speed=0;showNotif('⛔ Trilho bloqueado — repare antes de prosseguir')}else{this.train.x=nextX;if(!this.forestLoaded&&this.brokenRepaired&&this.train.x>16.5&&!this.transitioning)this.showTransition('Trem entrando na Floresta…','Trilhos restaurados','Prepare armas — esporos à frente',()=>this.loadForest())}if(this.train.x>465)this.train.x=-45;this.player.pos={...this.getTrainPoint('driver')};this._worldTimer+=dt;if(this._worldTimer>12&&!this.travelEvents.active){this._worldTimer=0;const event=this.travelEvents.roll(.45);if(event&&this.beginMenu()){this.train.throttle=0;const panel=document.getElementById('travel-event'),title=document.getElementById('travel-event-title');if(title)title.textContent=event.title;panel?.classList.add('active')}}}else if(this.playerState.is(PLAYER_STATES.DRIVING))this.transitionPlayer(PLAYER_STATES.IN_TRAIN);this.player.stamina.regen(dt)}
    const focus=this.train.inTrain?this.train:this.player.pos;this.camera.x+=(focus.x-this.camera.x)*Math.min(1,dt*6);this.camera.z+=(focus.z-this.camera.z)*Math.min(1,dt*6);
    const reload=this.pistol.tick(dt);if(reload?.completed)showNotif(`Recarregado ${reload.mag}/${this.pistol.magSize}`);this.profile.add('playTime',dt);
    for(const enemy of this.enemies){if(enemy.state==='DEAD')continue;enemy.ai.update(dt,this.player.pos);if(enemy.state==='ATTACK'){enemy._cd=(enemy._cd||0)-dt;if(enemy._cd<=0){enemy._cd=1.1;this.damagePlayer(enemy.damage||8);showNotif(`-${enemy.damage||8} de ${enemy.name}`)}}}
    if(this.boss&&this.boss.state!=='DEAD'){this.boss.ai.update(dt,this.player.pos);this.boss.updatePhase();const bar=document.getElementById('boss-bar');if(bar){bar.style.display='block';document.getElementById('boss-name').textContent=`${this.boss.name} FASE ${this.boss.phase+1}`;document.getElementById('bar-boss').style.width=`${this.boss.hp/this.boss.maxHp*100}%`;document.getElementById('boss-hp').textContent=`${Math.round(this.boss.hp/this.boss.maxHp*100)}%`}this.boss._attackCd=(this.boss._attackCd||0)-dt;const bossDistance=distance(this.boss,this.player.pos);if(this.boss._attackCd<=0&&bossDistance<4){this.damagePlayer(20+this.boss.phase*4);this.boss._attackCd=2.7;showNotif(`${this.boss.name}: Esmagamento!`)}}
    if(this.player.health.dead&&!this.playerState.is(PLAYER_STATES.DEAD)){this.train.speed=0;this.transitionPlayer(PLAYER_STATES.DEAD,{reason:'health-depleted'});this.playerAnimator.update(dt,{playerState:PLAYER_STATES.DEAD,grounded:true});const death=document.getElementById('death-screen');if(death)death.style.display='flex'}
    for(const particle of [...this.particlePool.active]){particle.life-=dt;particle.x+=particle.vx*dt;particle.z+=particle.vz*dt;particle.vx*=.92;particle.vz*=.92;if(particle.life<=0)this.particlePool.release(particle)}for(const projectile of [...this.projectilePool.active]){projectile.life-=dt;projectile.x+=projectile.vx*dt;projectile.z+=projectile.vz*dt;if(projectile.life<=0)this.projectilePool.release(projectile)}for(const remote of this.remotePlayers.values()){remote.x+=(remote.targetX-remote.x)*Math.min(1,dt*12);remote.z+=(remote.targetZ-remote.z)*Math.min(1,dt*12)}
    this.furnace.tick(dt);const furnaceBar=document.getElementById('furnace-bar');if(furnaceBar)furnaceBar.style.width=`${this.furnace.progress*100}%`;this.updateDashboard();this.updatePrompt();this._hudTimer-=dt;if(this._hudTimer<=0){this._hudTimer=.1;updateHUD({hp:this.player.health.current,stamina:this.player.stamina.current,lv:this.player.level,xp:this.player.xp,coins:this.player.coins,fuel:this.train.fuel,integ:this.train.integ,weapon:this.weapon==='sword'?'⚔️ Espada':`🔫 ${this.pistol.mag}/${this.pistol.magSize}`,region:this.currentRegion.name});this.renderObjective()}
    if(this.multiplayer){this.networkTimer-=dt;if(this.networkTimer<=0){this.networkTimer=.05;this.multiplayer.sendState({x:this.player.pos.x,z:this.player.pos.z,yaw:this.facing,speed:0});this.networkWorldTimer=(this.networkWorldTimer||0)-.05;if(this.multiplayer.isHost&&this.networkWorldTimer<=0){this.networkWorldTimer=.1;this.multiplayer.sendTrain({x:this.train.x,z:this.train.z,speed:this.train.speed,fuel:this.train.fuel});this.multiplayer.sendWorld({mobs:this.enemies.filter(enemy=>enemy.state!=='DEAD').map(enemy=>({id:enemy.baseId||enemy.id,x:enemy.x,z:enemy.z,hp:enemy.hp,state:enemy.state})),bosses:this.boss?[{id:this.boss.id,x:this.boss.x,z:this.boss.z,hp:this.boss.hp,state:this.boss.state}]:[],events:this.travelEvents.history.slice(-8)})}}}
    this._saveCd-=dt;if(this._saveCd<=0){this._saveCd=12;this.doSave(true)}
  }
  updateDashboard(){const dashboard=document.getElementById('train-dashboard');if(!dashboard)return;dashboard.classList.toggle('active',this.train.inTrain);for(const [key,value]of Object.entries({speed:this.train.speed.toFixed(1),distance:(this.train.routeProgress/1000).toFixed(1),fuel:Math.round(this.train.fuel),integrity:Math.round(this.train.integrity)})){const element=document.getElementById(`train-${key}`);if(element)element.textContent=value}const destination=document.getElementById('train-destination');if(destination)destination.textContent=`DESTINO: ${this.currentRegion.name.toUpperCase()}`}
  updatePrompt(){const prompt=document.getElementById('prompt');if(!prompt)return;let text='';if(this.train.inTrain)text='F sair • Q acelerar • E frear';else if(distance(this.player.pos,this.train)<2.8)text='E entrar / abastecer locomotiva';else if(!this.brokenRepaired&&Math.hypot(this.player.pos.x-14,this.player.pos.z-10)<3.5)text='R reparar trilho • 3 sucata + 2 lingotes';else{const resource=this.resources.find(item=>!item.depleted&&distance(item,this.player.pos)<2.4);const station=this.stations.find(item=>distance(item,this.player.pos)<2.4);const npc=this.npcs.find(item=>distance(item,this.player.pos)<2.4);if(resource)text=`E coletar ${resource.type}`;else if(station)text=`E usar ${station.type.replaceAll('_',' ')}`;else if(npc)text=`E conversar com ${npc.name}`}prompt.textContent=text}

  worldToScreen(x,z){return{x:(x-this.camera.x)*this.camera.zoom+this.width/2,y:(z-this.camera.z)*this.camera.zoom+this.height/2}}
  screenToWorld(x,y){return{x:(x-this.width/2)/this.camera.zoom+this.camera.x,z:(y-this.height/2)/this.camera.zoom+this.camera.z}}
  visible(x,z,padding=3){const point=this.worldToScreen(x,z),pad=padding*this.camera.zoom;return point.x>-pad&&point.x<this.width+pad&&point.y>-pad&&point.y<this.height+pad}
  drawGround(ctx){
    ctx.fillStyle='#3e6336';ctx.fillRect(0,0,this.width,this.height);if(this.patterns.grass){ctx.save();ctx.globalAlpha=.62;ctx.fillStyle=this.patterns.grass;ctx.translate((-this.camera.x*this.camera.zoom)%256,(-this.camera.z*this.camera.zoom)%256);ctx.fillRect(-256,-256,this.width+512,this.height+512);ctx.restore()}
    for(const region of REGIONS){const left=this.worldToScreen(region.bounds[0],0).x,right=this.worldToScreen(region.bounds[1],0).x;if(right<0||left>this.width)continue;ctx.fillStyle=REGION_TINTS[region.id];ctx.fillRect(left,0,right-left,this.height)}
    if((this.settings.vegetation??100)>0)for(const item of this.decor){if(!this.visible(item.x,item.z,1))continue;const point=this.worldToScreen(item.x,item.z),size=item.size*this.camera.zoom;ctx.globalAlpha=.28;if(item.type==='stone'){ctx.fillStyle='#8a867c';ctx.beginPath();ctx.ellipse(point.x,point.y,size*.55,size*.34,.4,0,TAU);ctx.fill()}else{ctx.strokeStyle='#90aa69';ctx.lineWidth=1;for(let index=0;index<3;index++){ctx.beginPath();ctx.moveTo(point.x,point.y);ctx.lineTo(point.x+(index-1)*size*.35,point.y-size*(.5+index*.1));ctx.stroke()}}ctx.globalAlpha=1}
  }
  drawRails(ctx){const from=this.screenToWorld(-60,0).x,to=this.screenToWorld(this.width+60,0).x,y=this.worldToScreen(0,10).y,scale=this.camera.zoom;ctx.strokeStyle='rgba(25,18,13,.68)';ctx.lineWidth=scale*.68;ctx.beginPath();ctx.moveTo(-60,y);ctx.lineTo(this.width+60,y);ctx.stroke();ctx.strokeStyle='#30231b';ctx.lineWidth=scale*.11;for(let x=Math.floor(from/1.35)*1.35;x<to;x+=1.35){const point=this.worldToScreen(x,10);ctx.beginPath();ctx.moveTo(point.x,point.y-scale*.58);ctx.lineTo(point.x,point.y+scale*.58);ctx.stroke()}for(const offset of [-.31,.31]){ctx.strokeStyle='#a5a29b';ctx.lineWidth=Math.max(2,scale*.09);ctx.beginPath();ctx.moveTo(-60,y+offset*scale);ctx.lineTo(this.width+60,y+offset*scale);ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.28)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-60,y+(offset-.04)*scale);ctx.lineTo(this.width+60,y+(offset-.04)*scale);ctx.stroke()}if(!this.brokenRepaired){const point=this.worldToScreen(14,10);ctx.fillStyle='rgba(92,17,12,.88)';ctx.fillRect(point.x-scale*.72,point.y-scale*.78,scale*1.44,scale*1.56);ctx.strokeStyle='#ff796d';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(point.x-scale*.45,point.y-scale*.4);ctx.lineTo(point.x+scale*.42,point.y+scale*.42);ctx.moveTo(point.x+scale*.42,point.y-scale*.4);ctx.lineTo(point.x-scale*.45,point.y+scale*.42);ctx.stroke()}}
  drawStation(ctx){if(!this.visible(2,12,5))return;const point=this.worldToScreen(2,12),scale=this.camera.zoom;ctx.save();ctx.translate(point.x,point.y);ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(0,scale*.35,scale*3.2,scale*1.8,0,0,TAU);ctx.fill();const roof=ctx.createLinearGradient(0,-scale*2,0,scale*1.5);roof.addColorStop(0,'#8d4b31');roof.addColorStop(1,'#442319');ctx.fillStyle=roof;ctx.strokeStyle='#c8955f';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(-scale*2.7,-scale*1.65,scale*5.4,scale*3.3,scale*.15);ctx.fill();ctx.stroke();ctx.strokeStyle='rgba(255,224,170,.25)';for(let x=-2.2;x<2.5;x+=.55){ctx.beginPath();ctx.moveTo(x*scale,-scale*1.5);ctx.lineTo(x*scale,scale*1.5);ctx.stroke()}ctx.fillStyle='#251914';ctx.fillRect(-scale*.48,-scale*1.65,scale*.96,scale*3.3);ctx.fillStyle='#d8b368';ctx.font=`700 ${Math.max(9,scale*.28)}px sans-serif`;ctx.textAlign='center';ctx.fillText('ESTAÇÃO',0,-scale*1.85);ctx.restore()}
  drawLandmarks(ctx){for(const landmark of this.regionalWorld.landmarks){if(!this.visible(landmark.x,landmark.z,3))continue;const point=this.worldToScreen(landmark.x,landmark.z),scale=this.camera.zoom,type=landmark.type;ctx.save();ctx.translate(point.x,point.y);if(type.includes('river')){ctx.lineCap='round';ctx.strokeStyle='rgba(45,67,48,.48)';ctx.lineWidth=scale*1.25;ctx.beginPath();ctx.moveTo(-scale*2.1,-scale*.7);ctx.bezierCurveTo(-scale*.9,-scale*1.15,scale*.35,scale*.95,scale*2.1,scale*.45);ctx.stroke();ctx.strokeStyle='#487b86';ctx.lineWidth=scale*.82;ctx.stroke();ctx.strokeStyle='rgba(180,222,223,.36)';ctx.lineWidth=scale*.12;ctx.stroke()}else if(type.includes('cave')||type.includes('tunnel')||type.includes('mine')){ctx.fillStyle='rgba(0,0,0,.38)';ctx.beginPath();ctx.ellipse(0,scale*.25,scale*1.25,scale*.72,0,0,TAU);ctx.fill();ctx.strokeStyle='#756b5e';ctx.lineWidth=scale*.3;ctx.beginPath();ctx.arc(0,0,scale*.72,Math.PI,TAU);ctx.stroke();ctx.fillStyle='#101414';ctx.beginPath();ctx.ellipse(0,scale*.1,scale*.58,scale*.45,0,0,TAU);ctx.fill()}else if(type.includes('tower')){ctx.fillStyle='rgba(0,0,0,.34)';ctx.beginPath();ctx.ellipse(0,scale*.38,scale*.8,scale*.48,0,0,TAU);ctx.fill();ctx.fillStyle='#5d554b';ctx.strokeStyle='#a6977b';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,scale*.58,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#292b29';ctx.beginPath();ctx.arc(0,0,scale*.27,0,TAU);ctx.fill();for(let index=0;index<4;index++){const angle=index/4*TAU;ctx.strokeStyle='#b0a17e';ctx.beginPath();ctx.moveTo(Math.cos(angle)*scale*.28,Math.sin(angle)*scale*.28);ctx.lineTo(Math.cos(angle)*scale*.75,Math.sin(angle)*scale*.75);ctx.stroke()}}else{ctx.fillStyle='rgba(0,0,0,.34)';ctx.beginPath();ctx.ellipse(0,scale*.35,scale*1.3,scale*.72,0,0,TAU);ctx.fill();const roof=ctx.createLinearGradient(0,-scale*.85,0,scale*.85);roof.addColorStop(0,type.includes('laboratory')?'#71818a':type.includes('ruin')?'#69635a':'#76503c');roof.addColorStop(1,type.includes('laboratory')?'#35444c':type.includes('ruin')?'#3d3933':'#3b271f');ctx.fillStyle=roof;ctx.strokeStyle='#b79a72';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(-scale*1.08,-scale*.76,scale*2.16,scale*1.52,scale*.12);ctx.fill();ctx.stroke();ctx.strokeStyle='rgba(240,220,180,.2)';for(let x=-.8;x<1;x+=.4){ctx.beginPath();ctx.moveTo(x*scale,-scale*.68);ctx.lineTo(x*scale,scale*.68);ctx.stroke()}ctx.fillStyle='#1b211f';ctx.fillRect(-scale*.22,-scale*.76,scale*.44,scale*1.52)}if(landmark.discovered){ctx.fillStyle='#f5d77b';ctx.shadowColor='#000';ctx.shadowBlur=3;ctx.font=`700 ${Math.max(9,scale*.23)}px sans-serif`;ctx.textAlign='center';ctx.fillText(type.replaceAll('_',' '),0,-scale*1.15);ctx.shadowBlur=0}ctx.restore()}}
  drawResource(ctx,node){if(node.depleted||!node.mesh.visible||!this.visible(node.x,node.z,2))return;const point=this.worldToScreen(node.x,node.z),scale=this.camera.zoom,ratio=node.hp/node.maxHp;ctx.save();ctx.translate(point.x,point.y);ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(0,scale*.25,scale*.7,scale*.32,0,0,TAU);ctx.fill();if(node.type==='tree'&&this.assets.tree){ctx.drawImage(this.assets.tree,-scale*.94,-scale*.88,scale*1.88,scale*1.72)}else if(['rock','coal','iron_ore','copper_ore','titanium_ore'].includes(node.type)&&this.assets.rock){const filters={rock:'none',coal:'grayscale(1) brightness(.28) contrast(1.25)',iron_ore:'sepia(.8) saturate(2.1) hue-rotate(330deg)',copper_ore:'sepia(.9) saturate(2.4) hue-rotate(345deg)',titanium_ore:'grayscale(.35) saturate(1.8) hue-rotate(185deg)'};ctx.filter=filters[node.type]||'none';ctx.drawImage(this.assets.rock,-scale*.75,-scale*.52,scale*1.5,scale);ctx.filter='none'}else if(node.type==='tree'){ctx.fillStyle='#3f2a1b';ctx.beginPath();ctx.arc(0,0,scale*.28,0,TAU);ctx.fill();for(let index=0;index<5;index++){const angle=index/5*TAU,radius=scale*(.35+(index%2)*.15);ctx.fillStyle=index%2?'#26452a':'#345c32';ctx.beginPath();ctx.arc(Math.cos(angle)*radius*.55,Math.sin(angle)*radius*.55,scale*.48,0,TAU);ctx.fill()}}else if(node.type==='herbs'){ctx.strokeStyle='#65a96f';ctx.lineWidth=Math.max(2,scale*.08);for(let index=0;index<6;index++){const angle=index/6*TAU;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(Math.cos(angle)*scale*.48,Math.sin(angle)*scale*.48);ctx.stroke()}}else{ctx.fillStyle=RESOURCE_COLORS[node.type]||'#777';ctx.strokeStyle='rgba(230,220,195,.36)';ctx.lineWidth=1.5;ctx.beginPath();for(let index=0;index<7;index++){const angle=index/7*TAU,radius=scale*(index%2?.42:.6);const x=Math.cos(angle)*radius,y=Math.sin(angle)*radius;if(index===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.closePath();ctx.fill();ctx.stroke();if(['crystal','ember_core'].includes(node.type)){ctx.shadowColor=RESOURCE_COLORS[node.type];ctx.shadowBlur=14;ctx.stroke()}}if(ratio<1){ctx.strokeStyle='#f2ca62';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,scale*.75,-Math.PI/2,-Math.PI/2+TAU*ratio);ctx.stroke()}ctx.restore()}
  drawNpc(ctx,npc){if(!this.visible(npc.x,npc.z,2))return;const point=this.worldToScreen(npc.x,npc.z),scale=this.camera.zoom;ctx.save();ctx.translate(point.x,point.y);ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(0,scale*.25,scale*.38,scale*.2,0,0,TAU);ctx.fill();ctx.fillStyle=npc.id==='mechanic'?'#385e70':npc.id==='herbalist'?'#446648':'#564b6e';ctx.beginPath();ctx.ellipse(0,0,scale*.34,scale*.5,0,0,TAU);ctx.fill();ctx.fillStyle='#b88965';ctx.beginPath();ctx.arc(0,-scale*.4,scale*.22,0,TAU);ctx.fill();ctx.fillStyle='#f3d070';ctx.font=`700 ${Math.max(9,scale*.22)}px sans-serif`;ctx.textAlign='center';ctx.fillText(npc.name,0,-scale*.78);ctx.restore()}
  drawStationObject(ctx,station){if(!this.visible(station.x,station.z,2))return;const point=this.worldToScreen(station.x,station.z),scale=this.camera.zoom;ctx.save();ctx.translate(point.x,point.y);ctx.fillStyle='rgba(0,0,0,.3)';ctx.fillRect(-scale*.72,-scale*.35,scale*1.5,scale*.85);ctx.fillStyle=station.type==='furnace'?'#554f4a':'#684125';ctx.strokeStyle='#b28a5f';ctx.lineWidth=2;ctx.fillRect(-scale*.65,-scale*.52,scale*1.3,scale*1.05);ctx.strokeRect(-scale*.65,-scale*.52,scale*1.3,scale*1.05);if(station.type==='furnace'){ctx.fillStyle='#e97029';ctx.shadowColor='#ff7b30';ctx.shadowBlur=12;ctx.beginPath();ctx.arc(0,0,scale*.2,0,TAU);ctx.fill()}ctx.restore()}
  drawTrain(ctx){if(!this.visible(this.train.x,this.train.z,8))return;const point=this.worldToScreen(this.train.x,this.train.z),scale=this.camera.zoom;ctx.save();ctx.translate(point.x,point.y);ctx.fillStyle='rgba(0,0,0,.42)';ctx.beginPath();ctx.ellipse(-scale*1.2,scale*.36,scale*(3.2+this.train.wagons.length*1.35),scale*.85,0,0,TAU);ctx.fill();for(let index=this.train.wagons.length-1;index>=0;index--){const wagon=this.train.wagons[index],x=-scale*(3.3+index*2.85);ctx.fillStyle=cssColor(wagon.color||'#66503c');ctx.strokeStyle='#ba9b69';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(x-scale*1.25,-scale*.72,scale*2.5,scale*1.44,scale*.14);ctx.fill();ctx.stroke();ctx.fillStyle='#171717';for(const wheelX of [-.75,.75]){ctx.beginPath();ctx.arc(x+wheelX*scale,scale*.72,scale*.2,0,TAU);ctx.fill()}if(wagon.type==='greenhouse'){ctx.fillStyle='rgba(116,190,141,.58)';ctx.fillRect(x-scale*.95,-scale*.48,scale*1.9,scale*.72)}if(wagon.type==='defensive'){ctx.fillStyle='#282828';ctx.beginPath();ctx.arc(x,0,scale*.28,0,TAU);ctx.fill()}}
    if(this.assets.locomotive){ctx.drawImage(this.assets.locomotive,-scale*2.5,-scale*.92,scale*5,scale*1.82)}else{const gradient=ctx.createLinearGradient(0,-scale,0,scale);gradient.addColorStop(0,'#b95838');gradient.addColorStop(1,'#552218');ctx.fillStyle=gradient;ctx.strokeStyle='#d2a13f';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(-scale*2.3,-scale*.8,scale*4.6,scale*1.6,scale*.18);ctx.fill();ctx.stroke()}ctx.restore()}
  drawCapybara(ctx,position,facing=this.facing,color=this.furColor,remote=false){if(!this.visible(position.x,position.z,2))return;const point=this.worldToScreen(position.x,position.z),scale=this.camera.zoom,jump=(position.y-.9)*scale*.62,bob=this.playerAnimator.state===PLAYER_ANIMATIONS.RUN?Math.sin(this.elapsed*14)*scale*.035:this.playerAnimator.state===PLAYER_ANIMATIONS.WALK?Math.sin(this.elapsed*9)*scale*.025:0;ctx.save();ctx.translate(point.x,point.y-jump+bob);ctx.rotate(facing);ctx.fillStyle='rgba(0,0,0,.34)';ctx.beginPath();ctx.ellipse(0,jump+scale*.18,scale*.92,scale*.42,0,0,TAU);ctx.fill();if(this.assets.capybara&&!remote){ctx.drawImage(this.assets.capybara,-scale*1.12,-scale*.74,scale*2.24,scale*1.49);if(color!=='#c49a6c'){ctx.globalCompositeOperation='source-atop';ctx.globalAlpha=.22;ctx.fillStyle=color;ctx.fillRect(-scale*1.12,-scale*.74,scale*2.24,scale*1.49);ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1}}else{const gradient=ctx.createLinearGradient(0,-scale*.6,0,scale*.6);gradient.addColorStop(0,remote?'#a9d5e5':color);gradient.addColorStop(1,remote?'#527c91':'#765039');ctx.fillStyle=gradient;ctx.beginPath();ctx.ellipse(-scale*.12,0,scale*.78,scale*.48,0,0,TAU);ctx.fill();ctx.beginPath();ctx.ellipse(scale*.66,0,scale*.46,scale*.38,0,0,TAU);ctx.fill();ctx.fillStyle='#33251d';ctx.beginPath();ctx.arc(scale*.98,scale*.02,scale*.1,0,TAU);ctx.fill();ctx.fillStyle='#17130f';ctx.beginPath();ctx.arc(scale*.74,-scale*.15,scale*.045,0,TAU);ctx.fill()}
    if(!remote){ctx.strokeStyle=this.weapon==='sword'?'#dfe9ed':'#25282a';ctx.lineWidth=this.weapon==='sword'?Math.max(3,scale*.1):Math.max(5,scale*.17);ctx.lineCap='round';const swing=this.playerAnimator.state===PLAYER_ANIMATIONS.ATTACK?Math.sin((this.elapsed*22)%Math.PI)*.65:0;ctx.rotate(swing);ctx.beginPath();ctx.moveTo(scale*.35,-scale*.32);ctx.lineTo(scale*(this.weapon==='sword'?1.38:1.02),-scale*.5);ctx.stroke();if(this.weapon==='sword'){ctx.strokeStyle='#8b5a2b';ctx.lineWidth=Math.max(3,scale*.12);ctx.beginPath();ctx.moveTo(scale*.28,-scale*.31);ctx.lineTo(scale*.5,-scale*.35);ctx.stroke()}}ctx.restore()}
  drawEnemy(ctx,enemy){if(enemy.state==='DEAD'||!this.visible(enemy.x,enemy.z,2))return;const point=this.worldToScreen(enemy.x,enemy.z),scale=this.camera.zoom,size=(enemy.boss?1.4:enemy.elite?1:.62)*scale,bob=Math.sin(this.elapsed*4+enemy.x)*scale*.035;ctx.save();ctx.translate(point.x,point.y+bob);ctx.fillStyle='rgba(0,0,0,.36)';ctx.beginPath();ctx.ellipse(0,size*.4,size*.75,size*.35,0,0,TAU);ctx.fill();const id=enemy.baseId||enemy.id,colors={slime:'#487b54',boar:'#72503b',wolf:'#786e62',spore:'#70517b',forest_guardian:'#4d2722'};ctx.fillStyle=colors[id]||(enemy.boss?'#552820':enemy.elite?'#61446f':'#6f5544');ctx.strokeStyle=enemy.elite?'#bd83d8':enemy.boss?'#e56b53':'rgba(230,210,170,.34)';ctx.lineWidth=enemy.boss?4:2;if(id==='wolf'){ctx.beginPath();ctx.moveTo(-size*.75,size*.35);ctx.lineTo(-size*.45,-size*.48);ctx.lineTo(size*.48,-size*.55);ctx.lineTo(size*.82,0);ctx.lineTo(size*.42,size*.48);ctx.closePath()}else if(id==='spore'){ctx.beginPath();ctx.arc(0,-size*.12,size*.72,Math.PI,TAU);ctx.lineTo(size*.38,size*.5);ctx.lineTo(-size*.38,size*.5);ctx.closePath()}else{ctx.beginPath();ctx.ellipse(0,0,size*.72,size*.52,0,0,TAU)}ctx.fill();ctx.stroke();ctx.fillStyle='#f4d67b';for(const side of [-1,1]){ctx.beginPath();ctx.arc(size*.42,side*size*.18,size*.07,0,TAU);ctx.fill()}if(enemy.hp<enemy.maxHp){ctx.fillStyle='rgba(0,0,0,.7)';ctx.fillRect(-size*.72,-size*.86,size*1.44,4);ctx.fillStyle='#c94c43';ctx.fillRect(-size*.72,-size*.86,size*1.44*(enemy.hp/enemy.maxHp),4)}ctx.restore()}
  drawEffects(ctx){for(const particle of this.particlePool.active){if(!this.visible(particle.x,particle.z,1))continue;const point=this.worldToScreen(particle.x,particle.z);ctx.globalAlpha=clamp(particle.life*2,0,1);ctx.fillStyle=particle.color;ctx.beginPath();ctx.arc(point.x,point.y,particle.size*this.camera.zoom,0,TAU);ctx.fill()}ctx.globalAlpha=1;for(const projectile of this.projectilePool.active){const point=this.worldToScreen(projectile.x,projectile.z);ctx.fillStyle=projectile.color;ctx.shadowColor=projectile.color;ctx.shadowBlur=10;ctx.beginPath();ctx.arc(point.x,point.y,Math.max(2,projectile.size*this.camera.zoom),0,TAU);ctx.fill();ctx.shadowBlur=0}}
  drawAtmosphere(ctx){const night=this.timeOfDay==='noite'||this.timeOfDay==='madrugada';if(night){ctx.fillStyle='rgba(5,12,29,.54)';ctx.fillRect(0,0,this.width,this.height)}if(this.weather==='fog'||this.weather==='neblina'){const fog=ctx.createRadialGradient(this.width/2,this.height/2,50,this.width/2,this.height/2,Math.max(this.width,this.height)*.72);fog.addColorStop(0,'rgba(205,218,209,.06)');fog.addColorStop(1,'rgba(188,201,193,.58)');ctx.fillStyle=fog;ctx.fillRect(0,0,this.width,this.height)}if(['rain','storm'].includes(this.weather)){ctx.strokeStyle='rgba(190,215,230,.36)';ctx.lineWidth=1;for(let index=0;index<90;index++){const x=(index*79+this.elapsed*260)%this.width,y=(index*137+this.elapsed*490)%this.height;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-5,y+15);ctx.stroke()}}const vignette=ctx.createRadialGradient(this.width/2,this.height/2,Math.min(this.width,this.height)*.2,this.width/2,this.height/2,Math.max(this.width,this.height)*.72);vignette.addColorStop(0,'rgba(0,0,0,0)');vignette.addColorStop(1,'rgba(0,0,0,.46)');ctx.fillStyle=vignette;ctx.fillRect(0,0,this.width,this.height)}
  draw(){const ctx=this.ctx;ctx.setTransform(this.pixelRatio,0,0,this.pixelRatio,0,0);ctx.clearRect(0,0,this.width,this.height);const shake=this.cameraShakeOffset||0;if(shake){ctx.save();ctx.translate((Math.random()-.5)*shake*this.camera.zoom,(Math.random()-.5)*shake*this.camera.zoom);this.cameraShakeOffset=Math.max(0,shake-.025)}this.drawGround(ctx);this.drawRails(ctx);this.drawLandmarks(ctx);this.drawStation(ctx);for(const node of this.resources)this.drawResource(ctx,node);for(const station of this.stations)this.drawStationObject(ctx,station);for(const npc of this.npcs)this.drawNpc(ctx,npc);for(const obstacle of this.obstacles)if(obstacle.tree)this.drawResource(ctx,{...obstacle,type:'tree',hp:1,maxHp:1,depleted:false,mesh:{visible:true}});this.drawTrain(ctx);for(const enemy of this.enemies)this.drawEnemy(ctx,enemy);if(this.boss)this.drawEnemy(ctx,this.boss);for(const remote of this.remotePlayers.values())this.drawCapybara(ctx,{x:remote.x,y:.9,z:remote.z},remote.facing,'#8ecae6',true);if(!this.train.inTrain)this.drawCapybara(ctx,this.player.pos);this.drawEffects(ctx);this.drawAtmosphere(ctx);if(shake)ctx.restore()}
  doSave(silent){const data={player:{level:this.player.level,xp:this.player.xp,coins:this.player.coins,pos:this.player.pos,train:this.train.toJSON(),equipment:this.equipment.toJSON()},inventory:inventory.toJSON(),hotbar:hotbarToJSON(),quests:this.quests.quests,profile:this.profile.toJSON(),reputation:this.reputation.toJSON(),missionCargo:this.missionCargo.toJSON(),world:{brokenRepaired:this.brokenRepaired,forestLoaded:this.forestLoaded,construction:this.construction.toJSON(),fog:this.fogOfWar.toJSON(),codex:this.codex.toJSON(),dialogue:this.dialogue.toJSON()}};const saved=this.saveMgr.save(data);if(!silent)showNotif(saved?'Jogo salvo':'Falha ao salvar');const button=document.getElementById('btn-continuar');if(button&&saved)button.disabled=false;return saved}
  loop(now=performance.now()){if(!this.running)return;requestAnimationFrame(next=>this.loop(next));const dt=Math.min(.05,Math.max(.001,(now-this.lastFrame)/1000));this.lastFrame=now;this.fps=Math.round(1/dt);if(!this._paused)this.update(dt);this.draw()}
  start(){if(this.running)return;this.running=true;this.lastFrame=performance.now();this.loop(this.lastFrame)}
}
